### ISSUE TITLE
Questions about tags named ZH and ZN

### ISSUE THREAD

**Issue by WZo0o** [Ahhgust/RtN#2]
Hello
After I run your software, I got a file named *.rtn.bam. And I noticed that all reads in this file have two tags ZH and ZN.
Do you have removed NUMTs from this file? 
If you did not remove NUMTs from this file, could I identify NUMTs based on these two tags? And if it is possible how can I do?

**Comment by Ahhgust** [comment]
Okay, well, first, I am really sorry-- I thought I had my github notifications turned on (in fact I do, so debugging that is next on my list!). 

As a recap: rtn maps each read against a database of numts (ZN) and of human mitochondrial references (ZH). The tags you refer to give the distance (the number of mismatches) with respect to the best alignment in each database. If the ZH tag is large (>2), then it is unlikely to be a true human sequence and the read is _masked_ by setting the mapping quality to 0. This implicitly removes the read from down-stream analyses, but you can still see them in tools like IGV.
 
Note that reads marked in this way may be numts, or they could be really noisy sequences (owing to non-independence in errors). Likewise, if a numt evolved recently it cannot be distinguished by rtn from true mitochondrial variation.

A quick and dirty approach to finding the reads marked by rtn is filter for mapping quality 0 reads; for completeness, I would remove them from the initial file, run rtn, and then filter the rtn file. Something like this should work:

samtools view -h _yourbam.rtn.bam_ | perl -e 'while (<>){ @s = split /\t/; if (/^@/ || $s[4] eq '0') { print $_ }};' | samtools view -b > possibleNumts.bam

Again, apologies for my late reply.
-August

**Comment by WZo0o** [comment]
Thanks for your reply
